### ISSUE TITLE
Not compatible with Gnome 45

### ISSUE THREAD

**Issue by davemmi** [dmzoneill/tado-gnome-shell-extension#1]
![Screenshot-20240321083238-1293x302](https://github.com/dmzoneill/tado-gnome-shell-extension/assets/157116516/ad2c39cb-059e-4eac-98a1-d37d20700bca)

**Comment by dmzoneill** [comment]
i pushed an update. im on 44, and cant test 45, but i dont see any issue with support for 45

**Comment by davemmi** [comment]
Got this message after trying to enable it: 

SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/shell/ui/main.js:3:0
